/*
**
** Copyright 2023 Cadence
** 
** Licensed under the Solderpad Hardware Licence, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
** 
**     https://solderpad.org/licenses/
** 
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
** 
*******************************************************************************
** CSR access test
** This tests consists of calling the functions generated by gen_csr_test.py 
** in the proper privilege modes. 
** It also checks that there are no expected exceptions that did not occur. 
** 
** Recomended method of invoking the gen_csr_test.py script is to run it the same 
** directory as this file with the following command line:
**
**  python3 gen_csr_test.py --csr_file ../../../../env/corev-dv/cv32e20_csr_template.yaml
**  
*******************************************************************************
*/

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "custom_handlers.h"
#include "riscv_csr_test_0.h"

volatile int glb_expect_illegal_insn    = 0;

volatile int  glb_csr_address = 0;

#define TEST_FAILED  *(volatile int*)(0x20000000) = 1
#define TEST_PASSED  *(volatile int*)(0x20000000) = 123456789

  

int main(int argc, char *argv[]) {
    interrupt_csr_check();
    machine_mode_check();
    if (glb_expect_illegal_insn != 0) {
      printf ("ERROR: Still expecting %d illegal instruction interrupt(s) at machine mode check.",
	      glb_expect_illegal_insn);
      TEST_FAILED;
    }	
    switch_to_user_mode();
    user_mode_check();
    if (glb_expect_illegal_insn != 0) {
      printf ("ERROR: Still expecting %d illegal instruction interrupt(s) at user mode check.",
	      glb_expect_illegal_insn);
      TEST_FAILED;
    }	
    switch_to_machine_mode();
    machine_mode_check();
    if (glb_expect_illegal_insn != 0) {
      printf ("ERROR: Still expecting %d illegal instruction interrupt(s) at end of test.",
	      glb_expect_illegal_insn);
      TEST_FAILED;
    }	
    TEST_PASSED;
}
